version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: docmgmt-postgres
    restart: always
    environment:
      POSTGRES_USER: docuser
      POSTGRES_PASSWORD: docpass
      POSTGRES_DB: docdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - doc-management-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docuser -d docdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: docmgmt-backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    networks:
      - doc-management-net
    volumes:
      - ./backend/uploads:/app/uploads
    command: sh -c "npm run seed:all && npm run start:prod"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: docmgmt-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - doc-management-net

volumes:
  pg_data:

networks:
  doc-management-net:
    driver: bridge